[versions]
pdfbox = "3.0.5"
tabula = "1.0.5"
poi = "5.4.1"
picocli = "4.7.7"
javafx = "21.0.7"
archunit = "1.4.2"
junit = "5.12.2"
openjfx-plugin = "0.1.0"

[libraries]
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
tabula = { module = "technology.tabula:tabula", version.ref = "tabula" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version.ref = "openjfx-plugin" }
